name: daily_stock

on:
  schedule:
    - cron: '0 23 * * *'   # 한국시간 매일 오전 08:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python stock_validator.py
        env:
          MY_EMAIL_SENDER: ${{ secrets.MY_EMAIL_SENDER }}
          MY_EMAIL_RECEIVER: ${{ secrets.MY_EMAIL_RECEIVER }}
          MY_EMAIL_PW: ${{ secrets.MY_EMAIL_PW }}

      - uses: actions/upload-artifact@v4
        with:
          name: stock-csv
          path: electronic_equipment_multi.csv

